CREATE TABLE PREDMET_16(
PNUM SMALLINT NOT NULL,
PNAME NCHAR(20) NULL,
HOURS SMALLINT NULL,
COURS TINYINT NULL
)
CREATE TABLE TEACHERS_16(
TNUM INTEGER NOT NULL,
TFAM NCHAR(20) NULL,
TIMA NCHAR(10) NULL,
TOTCH NCHAR(15) NULL,
TDATE DATETIME NULL
);

CREATE TABLE USP_16(
UNUM INTEGER NOT NULL,
OCENKA TINYINT NULL,
UDATE DATETIME NULL
);
