SELECT COUNT(DISTINCT SNUM) AS ' оличество студентов','студ. получают стипендию 'AS ' '
, STIP
FROM STUDENTS
WHERE EXISTS (SELECT OCENKA
FROM USP
WHERE UDATE = '1999-06-10 00:00:00')
GROUP BY STIP
ORDER BY 1 DESC